# Generated by Django 5.0.3 on 2024-03-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAlvar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='proyectos'),
        ),
    ]
