# Generated by Django 5.0.3 on 2024-03-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAlvar', '0002_alter_proyecto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='consulta',
            new_name='mensaje',
        ),
        migrations.AddField(
            model_name='consulta',
            name='tipo_consulta',
            field=models.IntegerField(choices=[(0, 'Consulta'), (1, 'Cita'), (2, 'Presupuesto'), (3, 'Otro tipo')], default=1),
            preserve_default=False,
        ),
    ]
