# Generated by Django 5.0.3 on 2024-03-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAlvar', '0003_rename_consulta_consulta_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos'),
        ),
    ]
